version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    environment:
      - MEILI_PUBLIC_KEY=null
    volumes:
      - ./meilisearch-data:/usr/src/app/data